# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e40fd1f2014e4dd76d3c6b17860adab961cf9383199f09912f4669cd4faeefd8be972731382cb13da04bc527e7248db1590ffa5d19c62960be240c97c972665

test:
  secret_key_base: 52114afe499308805af36a7d8aa459ca2cba582072290a880d3882cca7861054c06673af5e2199f0f4e105775b59a6215b4d45ea43d27ceaa3934e63f08b4792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
